### ISSUE TITLE
The collapse button wraps around on small screens

### ISSUE THREAD

**Issue by DASPELLER4** [DASPELLER4/Remote-Torrent-Downloader#1]
On small screens the collapse button may not be on the same line as the title of the folder

**Comment by JakeT23cool** [comment]
There is a slight mitigation of this issue in my pull request

**Comment by DASPELLER4** [comment]
> There is a slight mitigation of this issue in my pull request

Yep, the text is shorter, of course it still can possibly wrap around but it is less likely
